### ISSUE TITLE
The example sketch contains the wrong address

### ISSUE THREAD

**Issue by OakleyNode** [RobTillaart/ADG729#2]
Hello Mr. Tillaart,

I've just started testing an ADG729. I'm trying to share a single UART (rx/tx pins) with several EZO sensors. I started first with the Adafruit library, but I couldn't figure out how to enable both channels (1A and 1B). I was only able to get one-way communication from the sensor, but not send it anything. This is probably no fault of the library, but more my own inexperience.

So I switched over to your library, modified your example sketch, and voilà -- it works!! The dual channel function `MP.enableAB(0);` works great.

One thing I do notice, and did change in my own sketch, is that line 13 names the wrong address for the ADG279. I believe what is there is probably copy/pasted from your original code for the ADG278, as that is its address.

The object initiation...
`ADG729 MP(0x4C);  //  0x4C..0x4F`
... should be changed to...
`ADG729 MP(0x44);  // 0x44 ... 0x47`

I also see the README remarks that say that **The library is not tested with hardware yet.** I'm using it on a Nano33IOT and in my limited testing so far, it seems to work fine. I don't know what constitutes acceptable hardware testing in your view, but I plan to do a lot more testing on a variety of boards and ultimately will run this on a STM32L4+ in my fielded device, so I'd be happy to share those successes or failures with you here, if that would be of interest. I am a bit new to Github so not sure what's the proper way to do that (PR?), but if you provide some guidance I'll contribute anything I do learn with respect to the library.

Thanks for creating the library.
Cheers!
           ...Norm...

**Comment by RobTillaart** [comment]
Thanks for this feedback,
Great to hear the library works as intended. Wrote it together with related libs, see readme.

The address issue I need to look at.
Expect the address in the demo sketch is valid as the device can have different addresses. I might add a comment to it.
(update: it was not)

More feedback is very welcome, as I cannot test all possible configurations boards etc.

To learn GitHub, I advice to view some YouTube and create (fork) a playground project. Git is quite powerful with many commands however I mostly use a handful.

**Comment by RobTillaart** [comment]
You are right:

The ADG728 has 0x4C .. 0x4F
The ADG729 has address 0x44 .. 0x47

![image](https://github.com/user-attachments/assets/df61fe3d-4b80-40fa-a788-0735f01db65f)

**Comment by RobTillaart** [comment]
@OakleyNode 

All you need to know about git and more 

https://git-scm.com/book/en/v2

Also available as PDF

**Comment by RobTillaart** [comment]
@OakleyNode 

Created a develop branch and a PR to fix the example and the documentation.
Also added a convenience **getAddress()** function.

**Comment by RobTillaart** [comment]
@OakleyNode 

A new version 0.1.1 of the library is released with the fix.

Thanks for reporting this issue, appreciated!

**Comment by OakleyNode** [comment]
Thank you ! I will check out your GitHub learning recommendation. I will also provide updates on any relevant information I discover.
